import type { Metadata } from 'next'
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import MobileLayout from '@/components/ui/mobile-layout'
import { QueryProvider } from '@/providers/query-provider'

const geistSans = Geist({
 variable: '--font-geist-sans',
 subsets: ['latin'],
})

const geistMono = Geist_Mono({
 variable: '--font-geist-mono',
 subsets: ['latin'],
})

const plusJakartaSans = Plus_Jakarta_Sans({
 subsets: ['latin'],
 variable: '--font-plus-jakarta-sans',
})

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode
}>) {
 return (
  <html lang='en' className={`${plusJakartaSans.variable} h-dvh antialiased`}>
   <body className='flex min-h-dvh flex-col'>
    <QueryProvider>
     <MobileLayout>{children}</MobileLayout>
    </QueryProvider>
   </body>
  </html>
 )
}
